const videoConverterConfig = {
  ffmpegPath: "C:/path/to/ffmpeg",
  outputPath: "C:/path/to/output",
  presets: {
    globalFlags: ["-y"],
    input: "input.mp4",
    filterComplex: {
      split: {
        count: 5,
        outputs: ["v1080", "v720", "v540", "v360", "v240"],
      },
      scale: [
        {
          from: "v1080",
          to: "v1080out",
          resolution: { height: 1080 },
          flags: "bicubic",
          setsar: 1,
        },
        {
          from: "v720",
          to: "v720out",
          resolution: { height: 720 },
          flags: "bicubic",
          setsar: 1,
        },
        {
          from: "v540",
          to: "v540out",
          resolution: { height: 540 },
          flags: "bicubic",
          setsar: 1,
        },
        {
          from: "v360",
          to: "v360out",
          resolution: { height: 360 },
          flags: "bicubic",
          setsar: 1,
        },
        {
          from: "v240",
          to: "v240out",
          resolution: { height: 240 },
          flags: "bicubic",
          setsar: 1,
        },
      ],
    },
    maps: [
      "[v1080out]",
      "[v720out]",
      "[v540out]",
      "[v360out]",
      "[v240out]",
      "0:a:0",
    ],
    videoCodec: {
      codec: "libx264",
      pixFmt: "yuv420p",
      preset: "slow",
      x264Params: {
        keyint: 240,
        "min-keyint": 240,
        scenecut: 0,
        "open-gop": 0,
        "rc-lookahead": 40,
        ref: 5,
        bframes: 3,
        "aq-mode": 2,
        "aq-strength": 1.0,
        "psy-rd": 1.0,
        deblock: "-1:-1",
      },
    },
    representations: [
      {
        id: 0,
        crf: 21,
        maxrate: "5800k",
        bufsize: "11600k",
        profile: "high",
        level: "4.1",
      },
      {
        id: 1,
        crf: 22,
        maxrate: "3000k",
        bufsize: "6000k",
        profile: "high",
        level: "4.0",
      },
      {
        id: 2,
        crf: 23,
        maxrate: "1800k",
        bufsize: "3600k",
        profile: "main",
        level: "3.1",
      },
      {
        id: 3,
        crf: 24,
        maxrate: "1000k",
        bufsize: "2000k",
        profile: "main",
        level: "3.1",
      },
      {
        id: 4,
        crf: 26,
        maxrate: "600k",
        bufsize: "1200k",
        profile: "main",
        level: "3.0",
      },
    ],
    audio: {
      codec: "aac",
      channels: 2,
      sampleRate: 48000,
      bitrate: "128k",
    },
    keyFrameSettings: {
      force: "expr:gte(t,n_forced*4)",
      sceneChangeThreshold: 0,
    },
    dash: {
      segmentDuration: 4,
      useTimeline: 1,
      useTemplate: 1,
      initSegmentName: "init-$RepresentationID$.mp4",
      mediaSegmentName: "chunk-$RepresentationID$-$Number%05d$.m4s",
      adaptationSets: "id=0,streams=v id=1,streams=a",
      manifestName: "manifest.mpd",
    },
  },
};

export default videoConverterConfig;
